name: zs_dataset
input_size: [0,0]
task_name: uci_har # default task
is_normalize: null
patch_size: null

data_dir: "/scratch/leo/data/preprocessed_data/CLIP_downstream/${.task_name}" #"data/zs_dataset/${.task_name}"
fold: # place holder.
  fold_0:
    train: "None"
    val: "None"

task_config:
  uci_har:
    num_classes: 7
    head_type: classification
    is_normalize: true
    patch_size: 5

  wesad: 
    num_classes: 3
    head_type: classification
    is_normalize: false 
    patch_size: 25

  PPG_CVA:
    num_classes: 2
    head_type: classification
    is_normalize: false
    patch_size: 16 

  PPG_DM:
    num_classes: 2
    head_type: classification
    is_normalize: false
    patch_size: 6 

  PPG_HTN:
    num_classes: 4
    head_type: classification
    is_normalize: false
    patch_size: 4

  wisdm:
    num_classes: 18
    head_type: classification
    is_normalize: true
    patch_size: 15

  studentlife:
    num_classes: 3
    head_type: classification
    is_normalize: true 
    patch_size: 6 

  ptbxl:
    num_classes: 5
    head_type: classification
    is_normalize: false
    patch_size: 128 
    
  sleepEDF:
    num_classes: 5
    head_type: classification
    is_normalize: true
    patch_size: 25

  AsphaltObstacles:
    num_classes: 4
    head_type: classification
    is_normalize: false
    patch_size: 8
  
  Beijing_AQI:
    num_classes: 5
    head_type: classification
    is_normalize: true 
    patch_size: 6


sensor_aug: false
